/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OpenDictatorDslUiModule extends AbstractOpenDictatorDslUiModule {

	public OpenDictatorDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
