/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.openDictator.ui.internal.OpenDictatorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OpenDictatorDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(OpenDictatorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		OpenDictatorActivator activator = OpenDictatorActivator.getInstance();
		return activator != null ? activator.getInjector(OpenDictatorActivator.ORG_XTEXT_OPENDICTATOR_OPENDICTATORDSL) : null;
	}

}
