/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.openDictatorDsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class OpenDictatorDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PolicyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.Policy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIdKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cFailureMessageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFailureMessageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFailureMessageEStringParserRuleCall_3_0 = (RuleCall)cFailureMessageAssignment_3.eContents().get(0);
		private final Keyword cSuccessMessageKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSuccessMessageAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSuccessMessageEStringParserRuleCall_5_0 = (RuleCall)cSuccessMessageAssignment_5.eContents().get(0);
		private final Keyword cFileLocationKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInputfileAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cInputfileInputFileParserRuleCall_7_0 = (RuleCall)cInputfileAssignment_7.eContents().get(0);
		private final Keyword cPolicyKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cStatementsetAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cStatementsetStatementSetParserRuleCall_10_0 = (RuleCall)cStatementsetAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Policy returns Policy:
		//    'Id' id=EString
		//    'FailureMessage' FailureMessage=EString
		//    'SuccessMessage' SuccessMessage=EString
		//    'FileLocation' inputfile=InputFile
		//    'Policy' '{'statementset=StatementSet'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Id' id=EString
		//'FailureMessage' FailureMessage=EString
		//'SuccessMessage' SuccessMessage=EString
		//'FileLocation' inputfile=InputFile
		//'Policy' '{'statementset=StatementSet'}'
		public Group getGroup() { return cGroup; }
		
		//'Id'
		public Keyword getIdKeyword_0() { return cIdKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'FailureMessage'
		public Keyword getFailureMessageKeyword_2() { return cFailureMessageKeyword_2; }
		
		//FailureMessage=EString
		public Assignment getFailureMessageAssignment_3() { return cFailureMessageAssignment_3; }
		
		//EString
		public RuleCall getFailureMessageEStringParserRuleCall_3_0() { return cFailureMessageEStringParserRuleCall_3_0; }
		
		//'SuccessMessage'
		public Keyword getSuccessMessageKeyword_4() { return cSuccessMessageKeyword_4; }
		
		//SuccessMessage=EString
		public Assignment getSuccessMessageAssignment_5() { return cSuccessMessageAssignment_5; }
		
		//EString
		public RuleCall getSuccessMessageEStringParserRuleCall_5_0() { return cSuccessMessageEStringParserRuleCall_5_0; }
		
		//'FileLocation'
		public Keyword getFileLocationKeyword_6() { return cFileLocationKeyword_6; }
		
		//inputfile=InputFile
		public Assignment getInputfileAssignment_7() { return cInputfileAssignment_7; }
		
		//InputFile
		public RuleCall getInputfileInputFileParserRuleCall_7_0() { return cInputfileInputFileParserRuleCall_7_0; }
		
		//'Policy'
		public Keyword getPolicyKeyword_8() { return cPolicyKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//statementset=StatementSet
		public Assignment getStatementsetAssignment_10() { return cStatementsetAssignment_10; }
		
		//StatementSet
		public RuleCall getStatementsetStatementSetParserRuleCall_10_0() { return cStatementsetStatementSetParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class StatementSetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.StatementSet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStatementOperatorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStatementOperatorStatementOperatorEnumRuleCall_0_0 = (RuleCall)cStatementOperatorAssignment_0.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cStatementsetAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cStatementsetStatementSetParserRuleCall_2_0_0 = (RuleCall)cStatementsetAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cStatementsetAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cStatementsetStatementSetParserRuleCall_2_1_1_0 = (RuleCall)cStatementsetAssignment_2_1_1.eContents().get(0);
		private final Keyword cCommaKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cStatementAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStatementStatementParserRuleCall_3_0 = (RuleCall)cStatementAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStatementAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStatementStatementParserRuleCall_4_1_0 = (RuleCall)cStatementAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cStatementsetAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cStatementsetStatementSetParserRuleCall_5_1_0 = (RuleCall)cStatementsetAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cStatementsetAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cStatementsetStatementSetParserRuleCall_5_2_1_0 = (RuleCall)cStatementsetAssignment_5_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StatementSet returns StatementSet:
		//    statementOperator=StatementOperator
		//    '['
		//        ( statementset+=StatementSet ( "," statementset+=StatementSet)* ',')?
		//        statement+=Statement ( "," statement+=Statement)*
		//        ( ',' statementset+=StatementSet ( "," statementset+=StatementSet)* )?
		//    ']';
		@Override public ParserRule getRule() { return rule; }
		
		//statementOperator=StatementOperator
		//'['
		//    ( statementset+=StatementSet ( "," statementset+=StatementSet)* ',')?
		//    statement+=Statement ( "," statement+=Statement)*
		//    ( ',' statementset+=StatementSet ( "," statementset+=StatementSet)* )?
		//']'
		public Group getGroup() { return cGroup; }
		
		//statementOperator=StatementOperator
		public Assignment getStatementOperatorAssignment_0() { return cStatementOperatorAssignment_0; }
		
		//StatementOperator
		public RuleCall getStatementOperatorStatementOperatorEnumRuleCall_0_0() { return cStatementOperatorStatementOperatorEnumRuleCall_0_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//( statementset+=StatementSet ( "," statementset+=StatementSet)* ',')?
		public Group getGroup_2() { return cGroup_2; }
		
		//statementset+=StatementSet
		public Assignment getStatementsetAssignment_2_0() { return cStatementsetAssignment_2_0; }
		
		//StatementSet
		public RuleCall getStatementsetStatementSetParserRuleCall_2_0_0() { return cStatementsetStatementSetParserRuleCall_2_0_0; }
		
		//( "," statementset+=StatementSet)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//statementset+=StatementSet
		public Assignment getStatementsetAssignment_2_1_1() { return cStatementsetAssignment_2_1_1; }
		
		//StatementSet
		public RuleCall getStatementsetStatementSetParserRuleCall_2_1_1_0() { return cStatementsetStatementSetParserRuleCall_2_1_1_0; }
		
		//','
		public Keyword getCommaKeyword_2_2() { return cCommaKeyword_2_2; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_3() { return cStatementAssignment_3; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_3_0() { return cStatementStatementParserRuleCall_3_0; }
		
		//( "," statement+=Statement)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//statement+=Statement
		public Assignment getStatementAssignment_4_1() { return cStatementAssignment_4_1; }
		
		//Statement
		public RuleCall getStatementStatementParserRuleCall_4_1_0() { return cStatementStatementParserRuleCall_4_1_0; }
		
		//( ',' statementset+=StatementSet ( "," statementset+=StatementSet)* )?
		public Group getGroup_5() { return cGroup_5; }
		
		//','
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//statementset+=StatementSet
		public Assignment getStatementsetAssignment_5_1() { return cStatementsetAssignment_5_1; }
		
		//StatementSet
		public RuleCall getStatementsetStatementSetParserRuleCall_5_1_0() { return cStatementsetStatementSetParserRuleCall_5_1_0; }
		
		//( "," statementset+=StatementSet)*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//","
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }
		
		//statementset+=StatementSet
		public Assignment getStatementsetAssignment_5_2_1() { return cStatementsetAssignment_5_2_1; }
		
		//StatementSet
		public RuleCall getStatementsetStatementSetParserRuleCall_5_2_1_0() { return cStatementsetStatementSetParserRuleCall_5_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6() { return cRightSquareBracketKeyword_6; }
	}
	public class InputFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.InputFile");
		private final Assignment cFileLocationAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFileLocationEStringParserRuleCall_0 = (RuleCall)cFileLocationAssignment.eContents().get(0);
		
		//InputFile returns InputFile:
		//    fileLocation=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//fileLocation=EString
		public Assignment getFileLocationAssignment() { return cFileLocationAssignment; }
		
		//EString
		public RuleCall getFileLocationEStringParserRuleCall_0() { return cFileLocationEStringParserRuleCall_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.Statement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPrefixEvaluationOperatorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPrefixEvaluationOperatorEvaluationOperatorEnumRuleCall_0_0 = (RuleCall)cPrefixEvaluationOperatorAssignment_0.eContents().get(0);
		private final Assignment cJsonqueryAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cJsonqueryJsonQueryParserRuleCall_1_0 = (RuleCall)cJsonqueryAssignment_1.eContents().get(0);
		private final Assignment cEvaluationOperatorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEvaluationOperatorEvaluationOperatorEnumRuleCall_2_0 = (RuleCall)cEvaluationOperatorAssignment_2.eContents().get(0);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueValueParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//Statement returns Statement:
		//    ( prefixEvaluationOperator+=EvaluationOperator )? jsonquery=JsonQuery evaluationOperator=EvaluationOperator value=Value;
		@Override public ParserRule getRule() { return rule; }
		
		//( prefixEvaluationOperator+=EvaluationOperator )? jsonquery=JsonQuery evaluationOperator=EvaluationOperator value=Value
		public Group getGroup() { return cGroup; }
		
		//( prefixEvaluationOperator+=EvaluationOperator )?
		public Assignment getPrefixEvaluationOperatorAssignment_0() { return cPrefixEvaluationOperatorAssignment_0; }
		
		//EvaluationOperator
		public RuleCall getPrefixEvaluationOperatorEvaluationOperatorEnumRuleCall_0_0() { return cPrefixEvaluationOperatorEvaluationOperatorEnumRuleCall_0_0; }
		
		//jsonquery=JsonQuery
		public Assignment getJsonqueryAssignment_1() { return cJsonqueryAssignment_1; }
		
		//JsonQuery
		public RuleCall getJsonqueryJsonQueryParserRuleCall_1_0() { return cJsonqueryJsonQueryParserRuleCall_1_0; }
		
		//evaluationOperator=EvaluationOperator
		public Assignment getEvaluationOperatorAssignment_2() { return cEvaluationOperatorAssignment_2; }
		
		//EvaluationOperator
		public RuleCall getEvaluationOperatorEvaluationOperatorEnumRuleCall_2_0() { return cEvaluationOperatorEvaluationOperatorEnumRuleCall_2_0; }
		
		//value=Value
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_3_0() { return cValueValueParserRuleCall_3_0; }
	}
	public class JsonQueryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.JsonQuery");
		private final Assignment cQueryStringAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cQueryStringEStringParserRuleCall_0 = (RuleCall)cQueryStringAssignment.eContents().get(0);
		
		//JsonQuery returns JsonQuery:
		//    queryString=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//queryString=EString
		public Assignment getQueryStringAssignment() { return cQueryStringAssignment; }
		
		//EString
		public RuleCall getQueryStringEStringParserRuleCall_0() { return cQueryStringEStringParserRuleCall_0; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.Value");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//Value returns Value:
		//    'type=' type=EString ',' 'value=' value=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'type=' type=EString ',' 'value=' value=EString
		public Group getGroup() { return cGroup; }
		
		//'type='
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//'value='
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }
		
		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }
	}
	
	public class StatementOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.StatementOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cANDANDKeyword_0_0 = (Keyword)cANDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cORORKeyword_1_0 = (Keyword)cOREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNOTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNOTNOTKeyword_2_0 = (Keyword)cNOTEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum StatementOperator returns StatementOperator:
		//    AND = 'AND' | OR = 'OR' | NOT = 'NOT';
		public EnumRule getRule() { return rule; }
		
		//AND = 'AND' | OR = 'OR' | NOT = 'NOT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AND = 'AND'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration_0() { return cANDEnumLiteralDeclaration_0; }
		
		//'AND'
		public Keyword getANDANDKeyword_0_0() { return cANDANDKeyword_0_0; }
		
		//OR = 'OR'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration_1() { return cOREnumLiteralDeclaration_1; }
		
		//'OR'
		public Keyword getORORKeyword_1_0() { return cORORKeyword_1_0; }
		
		//NOT = 'NOT'
		public EnumLiteralDeclaration getNOTEnumLiteralDeclaration_2() { return cNOTEnumLiteralDeclaration_2; }
		
		//'NOT'
		public Keyword getNOTNOTKeyword_2_0() { return cNOTNOTKeyword_2_0; }
	}
	public class EvaluationOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.openDictatorDsl.OpenDictatorDsl.EvaluationOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFORSOMEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFORSOMEFORSOMEKeyword_0_0 = (Keyword)cFORSOMEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFORALLEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFORALLFORALLKeyword_1_0 = (Keyword)cFORALLEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCONTAINSEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCONTAINSCONTAINSKeyword_2_0 = (Keyword)cCONTAINSEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEQUALSEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEQUALSEQUALSKeyword_3_0 = (Keyword)cEQUALSEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLARGERTHANEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLARGERTHANLARGERTHANKeyword_4_0 = (Keyword)cLARGERTHANEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSMALLERTHANEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSMALLERTHANSMALLERTHANKeyword_5_0 = (Keyword)cSMALLERTHANEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum EvaluationOperator returns EvaluationOperator:
		//    FORSOME = 'FORSOME' | FORALL = 'FORALL' | CONTAINS = 'CONTAINS' | EQUALS = 'EQUALS' | LARGERTHAN = 'LARGERTHAN' | SMALLERTHAN = 'SMALLERTHAN';
		public EnumRule getRule() { return rule; }
		
		//FORSOME = 'FORSOME' | FORALL = 'FORALL' | CONTAINS = 'CONTAINS' | EQUALS = 'EQUALS' | LARGERTHAN = 'LARGERTHAN' | SMALLERTHAN = 'SMALLERTHAN'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FORSOME = 'FORSOME'
		public EnumLiteralDeclaration getFORSOMEEnumLiteralDeclaration_0() { return cFORSOMEEnumLiteralDeclaration_0; }
		
		//'FORSOME'
		public Keyword getFORSOMEFORSOMEKeyword_0_0() { return cFORSOMEFORSOMEKeyword_0_0; }
		
		//FORALL = 'FORALL'
		public EnumLiteralDeclaration getFORALLEnumLiteralDeclaration_1() { return cFORALLEnumLiteralDeclaration_1; }
		
		//'FORALL'
		public Keyword getFORALLFORALLKeyword_1_0() { return cFORALLFORALLKeyword_1_0; }
		
		//CONTAINS = 'CONTAINS'
		public EnumLiteralDeclaration getCONTAINSEnumLiteralDeclaration_2() { return cCONTAINSEnumLiteralDeclaration_2; }
		
		//'CONTAINS'
		public Keyword getCONTAINSCONTAINSKeyword_2_0() { return cCONTAINSCONTAINSKeyword_2_0; }
		
		//EQUALS = 'EQUALS'
		public EnumLiteralDeclaration getEQUALSEnumLiteralDeclaration_3() { return cEQUALSEnumLiteralDeclaration_3; }
		
		//'EQUALS'
		public Keyword getEQUALSEQUALSKeyword_3_0() { return cEQUALSEQUALSKeyword_3_0; }
		
		//LARGERTHAN = 'LARGERTHAN'
		public EnumLiteralDeclaration getLARGERTHANEnumLiteralDeclaration_4() { return cLARGERTHANEnumLiteralDeclaration_4; }
		
		//'LARGERTHAN'
		public Keyword getLARGERTHANLARGERTHANKeyword_4_0() { return cLARGERTHANLARGERTHANKeyword_4_0; }
		
		//SMALLERTHAN = 'SMALLERTHAN'
		public EnumLiteralDeclaration getSMALLERTHANEnumLiteralDeclaration_5() { return cSMALLERTHANEnumLiteralDeclaration_5; }
		
		//'SMALLERTHAN'
		public Keyword getSMALLERTHANSMALLERTHANKeyword_5_0() { return cSMALLERTHANSMALLERTHANKeyword_5_0; }
	}
	
	private final PolicyElements pPolicy;
	private final StatementSetElements pStatementSet;
	private final InputFileElements pInputFile;
	private final EStringElements pEString;
	private final StatementOperatorElements eStatementOperator;
	private final StatementElements pStatement;
	private final EvaluationOperatorElements eEvaluationOperator;
	private final JsonQueryElements pJsonQuery;
	private final ValueElements pValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public OpenDictatorDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPolicy = new PolicyElements();
		this.pStatementSet = new StatementSetElements();
		this.pInputFile = new InputFileElements();
		this.pEString = new EStringElements();
		this.eStatementOperator = new StatementOperatorElements();
		this.pStatement = new StatementElements();
		this.eEvaluationOperator = new EvaluationOperatorElements();
		this.pJsonQuery = new JsonQueryElements();
		this.pValue = new ValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.openDictatorDsl.OpenDictatorDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Policy returns Policy:
	//    'Id' id=EString
	//    'FailureMessage' FailureMessage=EString
	//    'SuccessMessage' SuccessMessage=EString
	//    'FileLocation' inputfile=InputFile
	//    'Policy' '{'statementset=StatementSet'}';
	public PolicyElements getPolicyAccess() {
		return pPolicy;
	}
	
	public ParserRule getPolicyRule() {
		return getPolicyAccess().getRule();
	}
	
	//StatementSet returns StatementSet:
	//    statementOperator=StatementOperator
	//    '['
	//        ( statementset+=StatementSet ( "," statementset+=StatementSet)* ',')?
	//        statement+=Statement ( "," statement+=Statement)*
	//        ( ',' statementset+=StatementSet ( "," statementset+=StatementSet)* )?
	//    ']';
	public StatementSetElements getStatementSetAccess() {
		return pStatementSet;
	}
	
	public ParserRule getStatementSetRule() {
		return getStatementSetAccess().getRule();
	}
	
	//InputFile returns InputFile:
	//    fileLocation=EString;
	public InputFileElements getInputFileAccess() {
		return pInputFile;
	}
	
	public ParserRule getInputFileRule() {
		return getInputFileAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum StatementOperator returns StatementOperator:
	//    AND = 'AND' | OR = 'OR' | NOT = 'NOT';
	public StatementOperatorElements getStatementOperatorAccess() {
		return eStatementOperator;
	}
	
	public EnumRule getStatementOperatorRule() {
		return getStatementOperatorAccess().getRule();
	}
	
	//Statement returns Statement:
	//    ( prefixEvaluationOperator+=EvaluationOperator )? jsonquery=JsonQuery evaluationOperator=EvaluationOperator value=Value;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//enum EvaluationOperator returns EvaluationOperator:
	//    FORSOME = 'FORSOME' | FORALL = 'FORALL' | CONTAINS = 'CONTAINS' | EQUALS = 'EQUALS' | LARGERTHAN = 'LARGERTHAN' | SMALLERTHAN = 'SMALLERTHAN';
	public EvaluationOperatorElements getEvaluationOperatorAccess() {
		return eEvaluationOperator;
	}
	
	public EnumRule getEvaluationOperatorRule() {
		return getEvaluationOperatorAccess().getRule();
	}
	
	//JsonQuery returns JsonQuery:
	//    queryString=EString;
	public JsonQueryElements getJsonQueryAccess() {
		return pJsonQuery;
	}
	
	public ParserRule getJsonQueryRule() {
		return getJsonQueryAccess().getRule();
	}
	
	//Value returns Value:
	//    'type=' type=EString ',' 'value=' value=EString;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
