/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.xtext.openDictator.services.OpenDictatorDslGrammarAccess

class OpenDictatorDslFormatter extends AbstractFormatter2 {
	
	@Inject extension OpenDictatorDslGrammarAccess
	
}
