/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.openDictatorDsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OpenDictatorDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/openDictatorDsl/parser/antlr/internal/InternalOpenDictatorDsl.tokens");
	}
}
