/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.openDictatorDsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OpenDictatorDslStandaloneSetup extends OpenDictatorDslStandaloneSetupGenerated {

	public static void doSetup() {
		new OpenDictatorDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
