/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.openDictatorDsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OpenDictatorDslRuntimeModule extends AbstractOpenDictatorDslRuntimeModule {
}
