/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.serializer;

import com.google.inject.Inject;
import java.util.Set;
import openDictator.InputFile;
import openDictator.OpenDictatorPackage;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.openDictator.services.OpenDictatorDslGrammarAccess;

@SuppressWarnings("all")
public class OpenDictatorDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private OpenDictatorDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == OpenDictatorPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case OpenDictatorPackage.INPUT_FILE:
				sequence_InputFile(context, (InputFile) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     InputFile returns InputFile
	 *
	 * Constraint:
	 *     fileLocation=EString
	 * </pre>
	 */
	protected void sequence_InputFile(ISerializationContext context, InputFile semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, OpenDictatorPackage.Literals.INPUT_FILE__FILE_LOCATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, OpenDictatorPackage.Literals.INPUT_FILE__FILE_LOCATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInputFileAccess().getFileLocationEStringParserRuleCall_3_0(), semanticObject.getFileLocation());
		feeder.finish();
	}
	
	
}
