/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.openDictator.ui.internal.OpenDictatorActivator;

public class OpenDictatorDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OpenDictatorActivator.getInstance().getInjector("org.xtext.openDictator.OpenDictatorDsl");
	}

}
