/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.openDictator.parser.antlr.internal.InternalOpenDictatorDslParser;
import org.xtext.openDictator.services.OpenDictatorDslGrammarAccess;

public class OpenDictatorDslParser extends AbstractAntlrParser {

	@Inject
	private OpenDictatorDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOpenDictatorDslParser createParser(XtextTokenStream stream) {
		return new InternalOpenDictatorDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "InputFile";
	}

	public OpenDictatorDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OpenDictatorDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
