/**
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.openDictator.services.OpenDictatorDslGrammarAccess;

@SuppressWarnings("all")
public class OpenDictatorDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private OpenDictatorDslGrammarAccess _openDictatorDslGrammarAccess;
}
