/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.openDictator.OpenDictatorDslRuntimeModule;
import org.xtext.openDictator.OpenDictatorDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OpenDictatorDslIdeSetup extends OpenDictatorDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OpenDictatorDslRuntimeModule(), new OpenDictatorDslIdeModule()));
	}
	
}
