/*
 * generated by Xtext 2.34.0
 */
package org.xtext.openDictator.ide;


/**
 * Use this class to register ide components.
 */
public class OpenDictatorDslIdeModule extends AbstractOpenDictatorDslIdeModule {
}
